FROM node:18-alpine

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

EXPOSE 3000

ARG BACKEND_IMAGE_SERVER_PROTOCOL
ARG ENV BACKEND_IMAGE_SERVER_HOSTNAME $BACKEND_IMAGE_SERVER_HOSTNAME
ARG NEXT_PUBLIC_BACKEND_SERVER
ARG NEXT_PUBLIC_SERVER_FETCH_BACKEND_SERVER

ENV BACKEND_IMAGE_SERVER_PROTOCOL $BACKEND_IMAGE_SERVER_PROTOCOL
ENV BACKEND_IMAGE_SERVER_HOSTNAME $BACKEND_IMAGE_SERVER_HOSTNAME
ENV NEXT_PUBLIC_BACKEND_SERVER $NEXT_PUBLIC_BACKEND_SERVER
ENV NEXT_PUBLIC_SERVER_FETCH_BACKEND_SERVER $NEXT_PUBLIC_SERVER_FETCH_BACKEND_SERVER

RUN npm run build

CMD [ "npm", "start" ]