FROM node:18-alpine

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

ARG BACKEND_IMAGE_SERVER_PROTOCOL
ARG BACKEND_IMAGE_SERVER_HOSTNAME
ARG NEXT_PUBLIC_BACKEND_SERVER

ENV BACKEND_IMAGE_SERVER_PROTOCOL $BACKEND_IMAGE_SERVER_PROTOCOL
ENV BACKEND_IMAGE_SERVER_HOSTNAME $BACKEND_IMAGE_SERVER_HOSTNAME
ENV NEXT_PUBLIC_BACKEND_SERVER $NEXT_PUBLIC_BACKEND_SERVER

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]